# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Meal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Meal
  pod "youtube-ios-player-helper", "~> 0.1"

  target 'The MealTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The MealUITests' do
    # Pods for testing
  end

end
